# Generated by Django 5.1.6 on 2025-03-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment_flagged_delete_flaggedcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='flagged',
            new_name='deleted',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
