# Generated by Django 5.1.6 on 2025-03-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_flagged_comment_deleted_comment_is_flagged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='deleted',
            new_name='flagged',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_flagged',
        ),
    ]
